// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACFPdV7Ahj1CT_eMTu-pM74r4U14iI8zw',
    appId: '1:1088758250930:web:17b9d24791ab4175ebb8ab',
    messagingSenderId: '1088758250930',
    projectId: 'cardealership-be8f9',
    authDomain: 'cardealership-be8f9.firebaseapp.com',
    storageBucket: 'cardealership-be8f9.appspot.com',
    measurementId: 'G-VD6VGD6QJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejKnyvc-Lr8rBnQzALuKGekPNZgS0Ayc',
    appId: '1:1088758250930:android:351120f185a47292ebb8ab',
    messagingSenderId: '1088758250930',
    projectId: 'cardealership-be8f9',
    storageBucket: 'cardealership-be8f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrj6oyiW-6uZLdRH6otElbP3w4uLT5G4',
    appId: '1:1088758250930:ios:77242366d761698febb8ab',
    messagingSenderId: '1088758250930',
    projectId: 'cardealership-be8f9',
    storageBucket: 'cardealership-be8f9.appspot.com',
    iosBundleId: 'com.example.cardealership',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMrj6oyiW-6uZLdRH6otElbP3w4uLT5G4',
    appId: '1:1088758250930:ios:77242366d761698febb8ab',
    messagingSenderId: '1088758250930',
    projectId: 'cardealership-be8f9',
    storageBucket: 'cardealership-be8f9.appspot.com',
    iosBundleId: 'com.example.cardealership',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACFPdV7Ahj1CT_eMTu-pM74r4U14iI8zw',
    appId: '1:1088758250930:web:f549904c2551b516ebb8ab',
    messagingSenderId: '1088758250930',
    projectId: 'cardealership-be8f9',
    authDomain: 'cardealership-be8f9.firebaseapp.com',
    storageBucket: 'cardealership-be8f9.appspot.com',
    measurementId: 'G-8QE8FMB10P',
  );
}
